# Generated by Django 3.1.7 on 2021-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('themePreference', models.IntegerField(default=0)),
                ('colorPreference', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dateTime', models.DateTimeField(verbose_name='date created')),
                ('contentPath', models.CharField(max_length=200)),
            ],
        ),
    ]
