# Generated by Django 3.1.7 on 2021-04-06 13:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='colorPreference',
            new_name='choice of color',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='themePreference',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='contentPath',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='diary',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='date created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 13, 44, 11, 62744, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='entry',
            name='parentDiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.diary'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
