# Generated by Django 3.1.7 on 2021-04-08 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210406_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='uuid',
            field=models.CharField(default='d2ded8ab-9bd1-47bd-a9cb-013666f6a78a', max_length=36),
        ),
        migrations.AddField(
            model_name='entry',
            name='uuid',
            field=models.CharField(default='6aaa75fe-baa3-4639-a762-f41761a9d9da', max_length=36),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 15, 24, 25, 594344, tzinfo=utc)),
        ),
    ]
