# Generated by Django 3.1.7 on 2021-04-08 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210408_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='uuid',
            field=models.CharField(default='21786b59-ed5e-47e4-a185-5dad76ad643c', max_length=36),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.CharField(default='a73deac2-68d2-410a-bcb4-25411d2f7ef1', max_length=36),
        ),
    ]
