# Generated by Django 3.1.7 on 2021-04-12 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20210412_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
