# Generated by Django 3.1.7 on 2021-04-13 00:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20210412_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
