# Generated by Django 3.1.7 on 2021-04-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20210413_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='choice of color',
            new_name='themePreference',
        ),
    ]
