# Generated by Django 3.1.7 on 2021-04-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20210413_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date created',
            new_name='dateTime',
        ),
    ]
